### PR TITLE
Added License file and project docs

### PR DESCRIPTION
**Pull request by ivanderk**
We need to provide identical basic project artifacts - ie. LICENSE file, Contributors guideines etc - in the root directory of each project

### CODE REVIEW

**Comment by dario-rodriguez** [comment]
Hello Iwan,

You are correct, I moved all of those files to the .github folder, instead of just moving the PR_TEMPLATE and the ISSUE_TEMPLATE.

Related the ISSUE_TEMPLATE file, IMHO the solution that you are proposing is not the correct. My proposal is to do that in the same was as cicdgen -> https://github.com/devonfw/cicdgen/ 

It enables you to have more than one ISSUE_TEMPLATE and when you create a new issue it will ask you for the template that you want to use. Example: 

imagen

**Comment by ivanderk** [comment]
Fine, but I am not "proposing". I took the files from devon4ng. So either we use that solution or take yours and then apply it to all other repos. Please coordinate with @sjimenez77

**Comment by dario-rodriguez** [comment]
Ok, I accept this solution now and when Santos come back I will discuss it with him.

**Comment by sjimenez77** [comment]
From my point of view we should change all the issue templates in all of our repositories. When I come back from holidays I will start coordinating it.

**Pull request merged**
